version: '3.8'

networks:
  currency_network:
    driver: bridge

services:
  api:
    build: .
    container_name: currency_exchange_api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - currency_network
    environment:
      FLASK_ENV: production
      MYSQL_HOST: mysql
      MYSQL_DATABASE: currency_exchange
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: gunicorn -w 4 -b 0.0.0.0:5000 src.app:app

  mysql:
    image: mysql:8.0 
    container_name: currency_mysql
    ports:
      - "3306:3306"
    networks:
      - currency_network
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: currency_exchange
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: currency_redis
    ports:
      - "6379:6379"
    networks:
      - currency_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: currency_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency_network

  celery:
    build: .
    container_name: currency_celery_worker
    depends_on:
      - rabbitmq
      - redis
    networks:
      - currency_network
    environment:
      FLASK_ENV: production
      MYSQL_HOST: mysql
      MYSQL_DATABASE: currency_exchange
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: celery -A src.app.celery worker --loglevel=info

volumes:
  db_data:
